### ISSUE TITLE
用了大神的示例测试报了一下错误，大神看下是什么问题！

### ISSUE THREAD

**Issue by liveinfutrue** [LazyNeo/vue-oss-uploader#2]
{"path":"/640cf77eef80e5d5483e43e7f0ca0bb6.png?uploads=","status":-1,"headers":{},"res":{"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":136,"keepAliveSocket":false,"requestUrls":["https://rent-house-cn.oss-cn-shenzhen.aliyuncs.com/640cf77eef80e5d5483e43e7f0ca0bb6.png?uploads="],"timing":null,"remoteAddress":"","remotePort":""}}

**Comment by LazyNeo** [comment]
这是啥报错啊？我好想没见过

**Comment by LazyNeo** [comment]
组件我最近更新到0.1.10 你更新下看看 旧版有bug的
